-- 创建话题表
CREATE TABLE topics (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    heat VARCHAR(50) NOT NULL,
    trend VARCHAR(50) NOT NULL,
    icon VARCHAR(10) NOT NULL,
    description TEXT NOT NULL,
    related_product_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (related_product_id) REFERENCES products(id) ON DELETE SET NULL
);