package com.dailydiscover.model;

import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
public class RelatedProduct {
    private Long id;
    private Long productId;
    private Long relatedProductId;
    private String relationType;
    private BigDecimal relationStrength;
    private Integer sortOrder;
    private Boolean isAutoGenerated;
    private String notes;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}