
#GET http://localhost:8081/api/recommendations?page=1&limit=10&category=&sort=default&search=
#Content-Type: application/json

GET http://localhost:8081/daily-discover/cart/1
#Accept: application/json


