

#GET http://5c0e6d45.r5.cpolar.top/daily-discover/events/date?date=2025-01-22
#Accept: application/json

POST https://api.siliconflow.cn/v1/chat/completions
Authorization: Bearer sk-rroaxqzfrhjktlzvyyblkowogdkfauwfyjdbcejmvoheskix
Content-Type: application/json

{
  "model": "Qwen/QVQ-72B-Preview",
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "image_url",
          "image_url": {
            "url": "https://sf-maas-uat-prod.oss-cn-shanghai.aliyuncs.com/dog.png",
            "detail": "auto"
          }
        }
      ]
    }
  ],
  "stream": false,
  "max_tokens": 512,
  "stop": [
    "null"
  ],
  "temperature": 0.7,
  "top_p": 0.7,
  "top_k": 50,
  "frequency_penalty": 0.5,
  "n": 1,
  "response_format": {
    "type": "text"
  }
}

POST https://api.deepseek.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer sk-271e72eb9797403a980c169e89c07416

{
    "model": "deepseek-chat",
    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
       {"role": "user", "content": "除夕夜"}
    ],
   "stream": false
}


POST http://localhost:8081/daily-discover/user/register
Accept: application/json
Content-Type: application/json

{
    "phoneNumber": "13800138000",
    "password": "yourPassword123",
    "nickname": "用户昵称"
}
